### ISSUE TITLE
Failure to "hydrate"

### ISSUE THREAD

**Issue by pieleric** [senzil/osticket-google-oauth2-plugin#2]
I'm following the installation instruction, on a Ubuntu 18.04 (with php 7.2). I've copied the whole content of the report in osTicket/include/tickets/ but it fails with such error:
`$ php make.php hydrate`

```
The PEAR repository has been removed from Composer 2.x
Hydrating :: lib/ohmy/auth/src => lib
PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/home/piel/development/osTicket/include/plugins/google-oauth2-plugin/lib/ohmy/auth/src): failed to open dir: No such file or directory in /home/piel/development/osTicket/include/plugins/google-oauth2-plugin/make.php:476
Stack trace:
#0 /home/piel/development/osTicket/include/plugins/google-oauth2-plugin/make.php(476): RecursiveDirectoryIterator->__construct('/home/piel/deve...', 4096)
#1 /home/piel/development/osTicket/include/plugins/google-oauth2-plugin/make.php(335): PluginBuilder->_hydrate(Array)
#2 /home/piel/development/osTicket/include/plugins/google-oauth2-plugin/make.php(240): PluginBuilder->run(Array, Array)
#3 /home/piel/development/osTicket/include/plugins/google-oauth2-plugin/make.php(699): Module->_run('make.php')
#4 {main}
  thrown in /home/piel/development/osTicket/include/plugins/google-oauth2-plugin/make.php on line 476
```

Any idea what's wrong?

**Comment by GalacticHero228** [comment]
I manually created the /lib/ohmy/auth/src directory it speaks of and was able to run the commands.
